ifdef::env-github[]
:experimental:
endif::env-github[]

# Changelog

include::meta.adoc[]

## {latest_revision}

- nixos update to `18.03`
+
[WARNING]
====
`vagrant provision` won't update nixos for you. You should re-create a devbox or manually update the nixos channel:

```
root@nixos> nix-channel --add https://nixos.org/channels/nixos-18.03 nixos
root@nixos> nixos-rebuild switch --upgrade
```
====

- remove the `geppetto` eclipse plugin
+
[NOTE]
====
The http://puppetlabs.github.io/geppetto/faq.html[Geppetto] eclipse plugin has been removed. The download link is dead. The project has been inactive since 2016.

As an alternative, you might want to use https://code.visualstudio.com[visual source code] which is now included in the box by default.
====

- Eclipse updated to v4.7 (Oxygen)
- `language-puppet` updated to `1.3.16`


## v3.6, 04/01/2018

- `language-puppet` updated to `1.3.13`
- Increase the disk size of the box from 40 to 50G
- `Albert` launcher improvements:
* open files & directories in `Nautilus` using Albert.
* 'restart', 'shutdown' the vm with Albert.

## v3.5, 24/10/2017

- Add `envPackages` to the box configuration
- Move some optional packages to local-configuration.nix

CAUTION: If you upgrade using `vagrant provision`, you will need to change your `ROOT_DIR/config/box.dhall` according to https://github.com/CIRB/devbox/blob/master/user/config/box.dhall#L26[its template] !

## v3.4, 03/10/2017
- mr reposities have been renamed to match `Bitbucket` structure. For instance:
+
```
~/projects/cicd/puppet/bos -> /projects/bric/bos/puppet-stack-bos
```
- Add `dhall` extension to config files
- Update nixos to `17.09`
- Update `cicd-shell` to v1.6
- Remove xmobar config

## v3.3, 28/08/2017

- Move browser choice logic in `local-configuration.nix`
- Move video driver setting in desktop-configuration (to support non virtualbox setting)
- Turn off virtualbox `accelate3d` by default (unsupported by `OS X`, doesn't seem to make a difference  on linux)
- Add the `docker-compose` package
- `language-puppet` updated to `1.3.8.1`
- `cicd-shell` updated to `v1.5`
- Deprecation of `devbox-novagrant`

## v3.2, 08/05/2017

- https://github.com/thestinger/termite[`termite`] is now the default terminal emulator (replacing `urxvt`)
+
[WARNING]
====
copy/paste is now bound to  kbd:[<Ctrl><Shift>c/v] instead of kbd:[<Ctrl><Alt>c/v]

Check out the file:///home/vagrant/.local/share/doc/devbox.html#_terminal_emulator_termite[updated documentation].
====

- the status bar now displays the active <<_layout>>
- fix random desktop freezes (due to taffybar crash)
- introduce a default persistent Eclipse configuration (available at `.eclipse/workspace`)
- Eclipse will always open in the first workspace `[1]` and Chrome in the last one `[9]`.
- enable the terminal and Chrome bookmarks extension in Albert
- `cicd-shell` updated to `v1.3`
- Add an overview schema in the README
- Since v3.0, `vagrant provision` has overridden both `/etc/nixos/local-configuration.nix` and `/etc/nixos/desktop-configuration.nix` with your configuration from ROOT_DIR.
+
When such personal config is not found in ROOT_DIR, the two system files are now also overridden but with their original sources from the devbox repository (a backup is available in case some changes were not propagated to the ROOT_DIR).

## v3.1, 14/04/2017

- add console configuration (light/dark color theme)
- fix missing `geppetto` eclipse plugin
- cicd-shell v1.1

## v3.0, 07/04/2017

### system configuration

#### packages

- update nixos to `17.03`
- https://albertlauncher.github.io/docs/[`albert`] (application launcher) on kbd:[<Control><Space>] replaces kbd:[<Super> p] (open menu)
- `cicd-shell` v1
- `eclipse` updated to `neon` (4.6)
- `yedit` and `jdt` (eclipse plugins) enabled by default (see `local-configuration.nix`)
- `nautilus` (file manager) enabled by default (see `local-configuration.nix`)
- replace `vim` with `neovim`
- replace `chromium` with `chrome`
- add `idea-community` and `idea-ultimate` to the list of suggested packages (see `local-configuration.nix`)

#### customization

- The nixos desktop/window manager configuration has been isolated in a new file called `desktop-configuration.nix`. Alike `local-configuratin.nix`, this file can be saved in your ROOT_DIR in case you want to use/try another desktop/window manager.
- ROOT_DIR `local-configuration.nix` and `desktop-configuration.nix` override their `/etc/nixos` counterpart when provisioning a new release (a backup file is created).

### user configuration

- The `params.sh` file has been replaced by two files:
* https://github.com/CIRB/devbox/blob/master/user/config/box[`config/box`] to configure the devbox
* https://github.com/CIRB/devbox/blob/master/user/config/box[`config/shell`] to configure the cicd-shell

- The key `repos` replaces the previous `user_stack` field and accepts a list of available `mr` repositories.
- The https://github.com/CIRB/vcsh_mr_template[mr template repository] is now generic and shouldn't be forked. The key `additionalRepos` deprecates the previous `mr_template_repo_url` field.
- possibility to choose among different wallpapers

Press `F1` for more detailed instructions.

[NOTE]
We are using https://github.com/Gabriel439/Haskell-Dhall-Library[`dhall`], a statically typed configuration format. You will be warned beforehand when a configuration file is invalid.


## v2.5, 11/02/2017

- Add default configuration for `vim`.
- Add `taffybar` a new status bar for xmonad.
+
The previous xmobar status bar is still available via `ln -sf xmonad-xmobar.hs ~/.xmonad/xmonad.hs`.

## v2.4, 23/01/2017

[WARNING]
.troubleshouting
====
While doing `vagrant provision` you might encounter an error related to an incompatible version of `local-configuration.nix`.
Indeed `vagrant provision` don't override that file as it might contain personal settings.

Please ensure that `/etc/nixos/local-configuration.nix` does not contain any `zsh` settings (these settings have been moved to `configuration.nix`). The file should look like https://github.com/CIRB/devbox/blob/master/system/local-configuration.nix + your personal settings.

If you need help, please join the `devbox` slack channel.
====

- Update `cicd-shell` to 0.9.7

## v2.3, 04/01/2017

- The puppet repository for your default stack is now automatically cloned in the project folder.
+
As an example, if you set in `params.sh` 'user_stack=fmx', the puppet repository for `fmx` will be cloned in `~/projects/cicd/puppet/fmx`.

## v2.2, 27/12/2016

- Add `cicd-shell`
- Update `language-puppet` to 1.3.4
- Add `zsh-completions` package

## v2.1, 02/12/2016

- Switch from `bash` to `zsh`

## v2.0, 01/12/2016

WARNING: 2.x breaks the compatibility of the `Vagrantfile`. Please fetch a new box (or update your local Vagrantfile)

- Add puppetdb-dns. This allows to looked for any machine known by `puppetdb` with a semantic name.
For instance if you want to connect through ssh to the `bos` jenkins slave, you would use:

```
→  ssh -i ~/.cirb_rsa username@jenkins.slave.bos.prod.cicd
```

## v1.4, 21/11/2016

- Include http://stash.cirb.lan/projects/CICD/repos/puppet-shared-scripts/browse/README.adoc[puppet doc] inside the README

## v1.3, 31/10/2016

- Add `fixlint` alias
+
To quickly fix puppet-lint errors and warnings (see <<_cicd>> )

## v1.2, 24/10/2016

- Add git `user.name` and `user.email` at provisioning time

## v1.1, 17/10/2016

- README improvements:
+
The README is now available offline within the box.
+
Press kbd:[F1] as usual to view it.
+
A revision tag (version, date) and  the changelog have been added. You always know which version of the box you are running.

## v1.0, 12/10/2016

* Initial release
