# DEVBOX
ifndef::env-github[]
include::meta.adoc[]
:env-devbox:
{latest_revision}
endif::env-github[]
:page-layout: docs
:toc: left
:toclevels: 2
:numbered:
:sectnumlevels: 1
:nofooter:
:icons: font
:docinfo1:
:source-language: bash
:source-highlighter: pygments
:experimental:
ifdef::env-github[]
:toc-placement: preamble
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::env-github[]


toc::[]

[.text-right]
icon:print[link="file:///home/vagrant/.local/share/doc/devbox.pdf"]

TIP: Have a quick look at the <<Troubleshooting>> section before to get started.


## Software requirements

- Virtualbox 5.1.x
- Vagrant 1.9.x

Please do update if you have older release(s).


## First time setup

### preparation

1. Within the host os (usually `Windows`), create a new folder of your choice. You might call it `devbox-x.x` where `x.x` is the major and minor version number of the devbox.
+
====
We will use the term `ROOT_DIR` to refer to this folder throughout the rest of the guide.
====
2. In `ROOT_DIR`, create a new config folder and copy the two files from the  https://github.com/CIRB/devbox/blob/master/user/config[config folder]. Modify them to match your personal settings:
+
```
mkdir config
curl -o config/box https://raw.githubusercontent.com/CIRB/devbox/master/user/config/box
curl -o config/shell https://raw.githubusercontent.com/CIRB/devbox/master/user/config/shell
```
+
WARNING: If you create the file manually, make sure you keep a `unix` file encoding.

### ssh keys

1. in the `ROOT_DIR`, create a directory `ssh-keys`.
2. in this ssh-keys subfolder, copy your `Bitbucket` key pair, rename them 'cirb_rsa' and 'cirb_rsa.pub' respectively if the filename differs.
3. in the ssh-keys subfolder, copy your `Github` key pair, rename them 'cirb_github_rsa' and 'cirb_github_rsa.pub'. If you use the same key pair, copy the previous pair and rename accordingly.

### box import

Open a terminal in the `ROOT_DIR`. You might want to use 'Git bash here' if you have a git client on your Windows host.

To download the base box from our CIRB repository:
```
vagrant box add devbox http://repo.irisnet.be/boxes/devbox.box <1>
```
<1> You can also use 'devbox-novagrant.box' and maintain a Vagrantfile locally

To initialize the box, in `ROOT_DIR` do:
```
vagrant init devbox && vagrant up
```

[NOTE]
====
- Always verify that the cable of the VM is connected as virtualbox (mainly older versions but has appeared with 5.1.2 too) has a bug not starting the network interface. If so, you will have to *connect the cable*. See <<Troubleshooting>>
- Do not interrupt the process. The first time it might take a while to update and fetch all the required components.
- In case any issue arises, please use the `#devbox` slack channel and ask for help.
====

When `vagrant up` terminates, restart your box in order to finalize your first time setup using:
```
vagrant reload
```


## Usage

WARNING: If you want to start the `devbox` from the Virtualbox UI, you should first uncomment https://github.com/CIRB/devbox/blob/058fd956c62e890a775b3c8ce709a855e7b0c758/system/local-configuration.nix#L20-L24[these lines] from local-configuration.nix. Otherwise the shared folder (/vagrant) won't be mounted. On the other hand the command line (`vagrant up`) will always mount the shared folder.

### vagrant

```
# boot the vm
vagrant up
# shutdown the vm
vagrant halt
# update system and user configuration
vagrant provision
# update user configuration only
vagrant provision --provision-with user
# update system configuration only
vagrant provision --provision-with system
# destroy the box (all local state is lost but the imported box remains)
vagrant destroy
# remove the imported box (necessary in case of a major version bump)
vagrant box remove devbox

```

#### provisioning

The provisioning is done automatically the first time `vagrant up` is executed. It is safe to provision on a regular basis using the `vagrant provision` command on the host. This will bring the new features listed in the <<_changelog>>. In case of a major version bump  a new devbox needs to be downloaded as described in <<_life_cycle>>.

Provisioning is separated into two steps:

- `vagrant provision --provision-with system`:
+
Update and (re)configure the system synchronizing the 'ROOT_DIR/local-configuration.nix'.
+
Updating the system takes a while and even more so if it is not done regularly.

- `vagrant provision --provision-with user`:
+
(Re)configuring the user is usually a quick task.
Given the personal settings defined in https://github.com/CIRB/devbox/blob/master/user/config/box[user/config/box], it will:
+
* setup your git config
* synchronize the `ROOT_DIR/ssh-keys` folder
* update all declared `mr` repositories including the https://github.com/CIRB/devbox-dotfiles[dotfiles repo]
* install/update the cicd shell
* install all required packages for working with the puppet stacks

### operating system

The devbox is based on https://nixos.org/[NixOS] version 17.03. NixOS is a Linux distribution based on the https://nixos.org/nix/[nix] package manager.

Compare to more traditional distributions, NixOS favors declarative settings and brings to the table the following properties:

- *reproducability*: everything is reproducible (packages are identical binary wise).
- *atomicity*: configuration changes can be rollback.
- *isolation*: on a project, user or system level, processes are built in an isolated environment.

By using `nixos` we are striving for a system that we can destroy and re-create at will without fuss.

The whole system setup is declared in the https://github.com/CIRB/devbox/blob/master/system/configuration.nix[/etc/nixos/configuration.nix] file.

#### useful command

```
# rebuild nixos after changing the system configuration file
→ sudo nixos-rebuild switch

# install a package in user space
→ nix-env -i atom

# search for a package
→ nq docker

# clean-up the store (whenever the disk usage is too high)
→ sudo nix-collect-garbage -d

```




### windows manager

The devbox comes with a https://en.wikipedia.org/wiki/Tiling_window_manager[tiling windows manager] called http://xmonad.org/[xmonad]. Such a minimal approach has been chosen for 3 reasons:

* Efficiency: the box needs to consume as minimum CPU/Mem resources as possible
* Simplicity: the window manager is basic but yet quite flexible
* Practicality: the desktop is distraction free.

#### minimal cheat sheet

|======
|Command |Description

| kbd:[<Super> t] |New terminal
| kbd:[<Super> 1..9] |Go to nth desktop
| kbd:[<Super> <Right>] | Go to next desktop
| kbd:[<Super> <Left>] | Go to previous desktop
| kbd:[<Super> <Shift> 1..9] |Switch to nth desktop
| kbd:[<Super> Space] |Change between horizontal, vertical and stack layout
| kbd:[<Super> Tab] |In stack layout, switch the stacked window
| kbd:[<Super> <Shift> c] |Close (kill) current window
| kbd:[<Super> m] kbd:[<Super> h] |Resize windows
| kbd:[F 1] |Open this README in a browser
|======

### terminal emulator

The `devbox` uses the `urxvt` terminal for its speed and customization.

|=====
|Command | Description

|kbd:[<Control> <Meta> p]|Change theme
|kbd:[<Control> <Shift> up/down] |Increase/Decrease font size
|kbd:[<Meta> <s>] |Search console output
|kbd:[<Control><Meta> c/v] | Copy/paste to/from clipboard
|=====

The default shell is `zsh` which allows for predictable history and completion.
You can revert to using `bash` as your default shell if you wish by removing all zsh related lines in the `/etc/nixos/local-configuration.nix` file.

You might want to enable some `oh-my-zsh` plugins by updating your zshrc. None has been enabled by default to avoid unwanted intrusion. See https://github.com/PierreR/dotfiles/blob/a8e45029767a22998f7a68fdf114297255495d0e/.zshrc#L3[here] for one example.


### projects

You can activate any available repository by setting `repos` in 'ROOT_DIR/config/box'. The list of available repositories is defined https://github.com/CIRB/vcsh_mr_template/tree/master/.config/mr/available.d[here] .

All enabled repos will be automatically cloned and configured into your box. For instance if `puppet-bos` is in the list of `repos`, you will find a `~/projects/cicd/puppet/bos` folder. In that case, the next step would be to go in that folder and to enter `make` on the command line.

To update all registered mr repository, do
```
→ mr -f up <1>
```
<1> you usually don't want to automatically update such repository on provisioning. That's the reason behind the `-f` (force) flag.

You can ask the `git status` of all repositories using

```
→ mr status
```

### cicd

You can use a semantic name as a `dns` to lookup any machine known by `puppetdb`. The pattern to use is: #$subgroup.$role.$hostgroup.zone.cicd#.

For instance if you want to connect through ssh to the `bos` jenkins slave, you can (inside the devbox) use:

```
→  ssh -i ~/.cirb_rsa username@jenkins.slave.bos.prod.cicd
```

In general you don't need to connect to nodes to manage, query or orchestrate them. Have a look at the <<_cicd_shell>> section to learn how to use the `cicd` command line utility.

For puppet help, go to the <<_puppet>> dedicated section.

## Customization

====
The customization of the devbox operates at different levels and makes sure every configuration - personal or shared - survives a `vagrant destroy`.
====

### system

You can add some specific configuration by editing `/etc/nixos/local-configuration.nix`.
For instance if you want to install the `geany` package, just uncomment the adhoc line in `local-configuration.nix`.

After changing the `local-configuration.nix` file, rebuild `nixos` with `nixos-rebuild switch` as root.

TIP: To avoid losing your customization after a `vagrant destroy`, copy `/etc/nixos/local-configuration.nix` into `/vagrant` on the boxfootnote:[The ROOT_DIR of the host is automatically mounted to /vagrant on the box given the box is started with `vagrant up`.]. If such a file exists on the ROOT_DIR of the host, it will be used the first time a box is provisioned and won't be overridden by a call to `vagrant provision` later on.

WARNING: More drastic changes such a changing the window manager is only possible via `/etc/nixos/configuration.nix`.

### user

#### install local packages

To install a package, just do:

```
→ nix-env -i geany <1>
```
<1> install the `geany` package for the vagrant user. The suffix _env_ expresses the fact that only the user environment is affected.

This imperative approach is quite useful for testing but the change is not recorded and won't survive a `vagrant destroy`. When you settle down on a list of packages, please add them to `local-configuration.nix` to gain persistence.

You can quickly search for packages online at https://nixos.org/nixos/packages.html[nixos.org]

#### available mr repositories

The devbox allows to quickly share any configuration across users. This is done by first adding a new `mr` source repository to the list of available repos https://github.com/CIRB/vcsh_mr_template/tree/master/.config/mr/available.d[in the mr CIRB template repository].

For instance, let say you want to propose some eclipse (or geany, atom, ...) setup as a base eclipse configuration for the CIRB. First create a git repository with the configuration files, then write a `.mr` file and propose it via  a pull request to the mr CIRB template repository. As soon as the PR is merged, any devbox user will be able to activate the new config by adding it to the list of its `repos` in `ROOT_DIR/config/box`.

#### generic dotfiles

The standard https://github.com/CIRB/devbox-dotfiles[CIRB dotfiles repositry] maintains a very general non specific default configuration for the devbox. It is continuously evolving and improving. Please feel welcomed to propose any change via a pull request.

#### personal mr repositories

You can register any source repository by adding it to the `additionalRepos` in `ROOT_DIR/config/box`. This is for personal configuration that you don't want to share. Once register, you update the user configuration with `mr up`.


## How is the box generated ?

The box is generated using packer and the source files from https://github.com/zimbatm/nixbox[here]:

```
packer.exe build nixos-x86_64.json <1>
vagrant box add devbox-x.x-pre packer_virtualbox-iso_virtualbox.box
```
<1> be careful of keeping the linux file encoding while working on windows !

The size of the 'pre box' is ~ 300M

The box is then repackaged to a full vm:

```
git clone git@github.com:CIRB/devbox.git
cd devbox
vagrant up --no-provision
vagrant provision --provision-with system
vagrant reload
rm -rf /tmp/system # on the future packaged box
vagrant package --output devbox-x.x.x --vagrantfile Vagrantfile
```

The size of the repackaged vagrant box is ~ 2G.


[[Troubleshooting]]
## Troubleshooting

Ssh-key with passphrase::
+
Using cirb ssh-keys with a passphrase will currently cause difficulties with `mr`, a tool we use to handle git repositories in a declarative way. It will prevent some of the automation to go through (nothing critical though). If possible, please regenerate a pair of keys with no passphrase and register them in stash.cirb.lanfootnote:[We will improve the situation in a future release if it is tagged as a major concern.].

Virtualbox 5.0.x::
+
For some host OS, Vagrant does not start its network interface. You will need to manually go to menu:Machine[Configuration > Network] and ensure the box "Cable Connected" is checked.
This issue has also been encountered with virtualbox 5.1.2

For Windows 10 users::
+
Everything usually just works on Windows 10.
That said, keep in mind that various issues have been reported concerning incompatibilities between `hyper-v` and `virtualbox`. It is likely that such compatibilities arise again after a windows or virtualbox update.
+
We will try to offer a hyper-v compatible box using `packer` (no virtualbox) in the future. Packer has just announced such a support. Stay tune.
+
In the meanwhile, if you face such a issue you will have to disable hyper-v to get a working devbox. Please proceed as follow:
+
[lowerroman]
. disable hyper-v
. use virtualbox as hypervisor
. install the docker tools based on a virtualbox machine.

NOTE: The only use of hyper-v we have detected so far is by the latest version of *Docker for Windows*.


## Life cycle

Tickets and issues are handled directly on https://github.com/CIRB/devbox/issues[Github issues]. Alternatively you might want to use http://jira.cirb.lan/browse/CICDPROJ-150[Jira].

Question, support, discussion are handled in the slack `#devbox` channel.

The versioning scheme used is semantic: `major.minor.patch`. A major jump (which is expected two or three times a year) implies some incompatible changes. Please look at the https://github.com/CIRB/devbox/blob/master/CHANGELOG.adoc[Changelog] for more information.

Here are the steps to migrate:

====
[lowerroman]
. destroy the old box losing all current statefootnote:[The README describes several tricks to keep/store your customization.] : `vagrant destroy`
. remove the old box: `vagrant box remove devbox`
. add the new one: `vagrant box add devbox http://repo.irisnet.be/boxes/devbox.box`
. initialize the new box: `vagrant init devbox && vagrant up`
====

TIP: You might prefer to keep the old devbox and create a new one to be 100% sure not to lose anything. Just pick another name when adding and initiating the box with vagrant. A good tip is to use `devbox-x.x` where `x.x` is the major and minor version of the box.


The devbox will be maintained continuously with at least a major release every six months to follow the OS life cycle.

ifndef::env-github[]

:leveloffset: +1

include::puppet.adoc[]

include::cicd-shell.adoc[]

include::CHANGELOG.adoc[]

:leveloffset: -1

endif::env-github[]
